version: 0.0.3
config:
    project:
        name: my-avs-project
        version: 0.1.0
        context: devnet
        project_uuid: a62df51c-2530-46e4-bc02-d2116641341f
        telemetry_enabled: true
        templateBaseUrl: https://github.com/Layr-Labs/hourglass-avs-template
        templateVersion: v0.1.0
        templatelanguage: go
